// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWI-zrMo-GIFwMjhBU_0JT21RkIsX2iCw',
    appId: '1:183635646847:web:2b76222e1e52a57c6c624a',
    messagingSenderId: '183635646847',
    projectId: 'absensifaceapp-mahaputra',
    authDomain: 'absensifaceapp-mahaputra.firebaseapp.com',
    storageBucket: 'absensifaceapp-mahaputra.firebasestorage.app',
    measurementId: 'G-MPY18L6WTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj8wfu7Snzh0kGrYomfWV4gyxJMZrUtDQ',
    appId: '1:183635646847:android:49e1ba6767cb00ce6c624a',
    messagingSenderId: '183635646847',
    projectId: 'absensifaceapp-mahaputra',
    storageBucket: 'absensifaceapp-mahaputra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWYDZfV0_BLoqRVVfwikX1iHiCYKN3ncw',
    appId: '1:183635646847:ios:b3c058931d099eed6c624a',
    messagingSenderId: '183635646847',
    projectId: 'absensifaceapp-mahaputra',
    storageBucket: 'absensifaceapp-mahaputra.firebasestorage.app',
    iosBundleId: 'com.example.faceAbsensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWYDZfV0_BLoqRVVfwikX1iHiCYKN3ncw',
    appId: '1:183635646847:ios:b3c058931d099eed6c624a',
    messagingSenderId: '183635646847',
    projectId: 'absensifaceapp-mahaputra',
    storageBucket: 'absensifaceapp-mahaputra.firebasestorage.app',
    iosBundleId: 'com.example.faceAbsensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWI-zrMo-GIFwMjhBU_0JT21RkIsX2iCw',
    appId: '1:183635646847:web:0b7c4359d11711e36c624a',
    messagingSenderId: '183635646847',
    projectId: 'absensifaceapp-mahaputra',
    authDomain: 'absensifaceapp-mahaputra.firebaseapp.com',
    storageBucket: 'absensifaceapp-mahaputra.firebasestorage.app',
    measurementId: 'G-KCQQK1D084',
  );
}
